z = int(input('Para saber a tabuada digite um número'))
print('{} x {:2} = {} '.format(z, 1, z*1))
print('{} x {:2} = {}'.format(z, 2, z*2))
print('{} x {:2} = {}'.format(z, 3, z*3))
print('{} x {:2} = {}'.format(z, 4, z*4))
print('{} x {:2} = {}'.format(z, 5, z*5))
print('{} x {:2} = {}'.format(z, 6, z*6))
print('{} x {:2} = {}'.format(z, 7, z*7))
print('{} x {:2} = {}'.format(z, 8, z*8))
print('{} x {:2} = {}'.format(z, 9, z*9))
print('{} x {:2} = {}'.format(z, 10, z*10))

